### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by dwt** [terminal-labs/lektor-debug#3]
Hi there,

I tried using your plugin in my lector project, and got this failure:

```
  E projects/index.html (TypeError: Markdown.__init__() takes from 2 to 3 positional arguments but 4 were given)
```

in `lektor server` it looks like this:

```
Traceback (most recent call last):
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/lektor/builder.py", line 900, in update
    yield ctx
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/lektor/builder.py", line 1151, in build_artifact
    build_func(artifact)
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/lektor/build_programs.py", line 191, in build_artifact
    artifact.render_template_into(self.source["_template"], this=self.source)
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/lektor/builder.py", line 724, in render_template_into
    rv = self.build_state.env.render_template(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/lektor/environment/__init__.py", line 296, in render_template
    return self.jinja_env.get_or_select_template(name).render(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/dwt/Code/Projekte/homepage/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dwt/Code/Projekte/homepage/templates/homepage.html", line 3, in top-level template code
    {% from "macros/blog.html" import render_blog_post, render_categories_from_blog_post %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dwt/Code/Projekte/homepage/templates/page.html", line 39, in top-level template code
    {% include 'includes/footer.html' %} {% debug %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dwt/Library/Caches/Lektor/packages/5aea3a62621d3a2bbc5bb67c73974584/lektor_debug.py", line 42, in _render
    md = Markdown(md_str, record, options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Markdown.__init__() takes from 2 to 3 positional arguments but 4 were given
```

Does this ring a bell for you? I guess you might have already fixed this but maybe haven't released the update to pypi?

**Comment by dwt** [comment]
Scratch that, the current released version of lektor 3.3.12 is actually too old to work with this plugin. my bad.

**Comment by narun4sk** [comment]
@dwt can you elaborate more? I'm facing the same issue :roll_eyes:

Nevermind, looks like it works with the beta release:
```
pip install Lektor==3.4.0b12
```

**Comment by dwt** [comment]
The current version of this plugin only worked with an unreleased version of lector. You need to either go to the builtin debug plugin (which can do less) or upgrade to the tip of the tree version of lector to use it. (I guess).

I have gone back to the builtin debug command and lived with it since.
